version: '1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb-drupal10
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal



  drupal:
    image: drupal:10.1.2-php8.1-apache-bullseye
    container_name: drupal10
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 8082:80
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html
  
networks:
  external: 
    driver: bridge
  internal:
    driver: bridge
  
volumes:
  drupal-data:
  db-data: