version: '1'

services:
  mariadbd7:
    image: mariadb
    container_name: mariadb-drupal7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data-d7:/var/lib/mysql
    networks:
      - internal
      - shared



  drupal7:
    image: drupal:7-php8.0-apache-bullseye
    container_name: drupal7
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html/d7

  mariadbd10:
    image: mariadb
    container_name: mariadb-drupal10
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data-d10:/var/lib/mysql
    networks:
      - internal



  drupal10:
    image: drupal:10.1.2-php8.1-apache-bullseye
    container_name: drupal10
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 8082:81
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html/d10

networks:
  external: 
    driver: bridge
  internal:
    driver: bridge
  shared:
    driver: bridge
  
volumes:
  drupal-data:
  db-data-d7:
  db-data-d10: