version: '1'
 
volumes:
  drupal-data:
  db-data-d7:
  db-data-d10:

services:
  mariadb7:
    image: mariadb
    container_name: mariadb-drupal7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data-d7:/var/lib/mysql
    networks:
      - internal
      - shared



  drupal7:
    image: drupal:7-php8.0-apache-bullseye
    container_name: drupal7
    depends_on:
      - mariadb7
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/drupal

  mariadb10:
    image: mariadb
    container_name: mariadb-drupal10
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data-d10:/var/lib/mysql
    networks:
      - internal



  drupal10:
    image: drupal:10.1.2-php8.1-apache-bullseye
    container_name: drupal10
    depends_on:
      - mariadb10
    restart: unless-stopped
    ports:
      - 8082:80
    networks:
      - internal
      - external
      - shared
    volumes:
      - drupal-data:/drupal

networks:
  external: 
    driver: bridge
  internal:
    driver: bridge
  shared:
    driver: bridge
 