version: '1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb-drupal7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3307:3306
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal
      - external



  drupal:
    image: drupal:7-php8.0-apache-bullseye
    container_name: drupal7
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - internal
      - external
    volumes:
      - drupal-data:/var/www/html
  
networks:
  external: 
    driver: bridge
  internal:
    driver: bridge
  
volumes:
  drupal-data:
  db-data: